title: Sentiment Analysis Using BigInsights for Hadoop
description: Ashiqur Rahman, Software Technology Lab, Queen's University, Kingston, Canada
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
include:
  - "_images"
